# Generated by Django 2.2.6 on 2020-05-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=25)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
    ]
